# Generated by Django 4.0.4 on 2022-05-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, max_length=300)),
                ('link', models.URLField(blank=True, null=True)),
                ('media', models.ImageField(upload_to='works/images')),
            ],
        ),
    ]
